name: JoinFeaturesDeluxe
main: net.zdany.joinfeaturesdeluxe.JoinFeaturesDeluxe
version: 1.2.2
authors: [ zDany ]
description: Adds customizable join features.
softdepend: [ PlaceholderAPI ]
permissions:
  joinfeaturesdeluxe.*:
    description: Permission of JoinMessagesDeluxe
    default: op
    children:
      joinfeaturesdeluxe.public.join-quit: true
      joinfeaturesdeluxe.public.first-join: true
      joinfeaturesdeluxe.private.join: true
      joinfeaturesdeluxe.private.first-join: true
      joinfeaturesdeluxe.join-title: true
  joinfeaturesdeluxe.all:
    description: Permission of JoinMessagesDeluxe
    default: op
    children:
      joinfeaturesdeluxe.public.join-quit: true
      joinfeaturesdeluxe.public.first-join: true
      joinfeaturesdeluxe.private.join: true
      joinfeaturesdeluxe.private.first-join: true
      joinfeaturesdeluxe.join-title: true
      joinfeaturesdeluxe.join-commands.join: true
      joinfeaturesdeluxe.join-commands.quit: true
  joinfeaturesdeluxe.public.join-quit:
    description: Permission of JoinMessagesDeluxe
    default: op
  joinfeaturesdeluxe.public.first-join:
    description: Permission of JoinMessagesDeluxe
    default: op
  joinfeaturesdeluxe.private.join:
    description: Permission of JoinMessagesDeluxe
    default: op
  joinfeaturesdeluxe.private.first-join:
    description: Permission of JoinMessagesDeluxe
    default: op
  joinfeaturesdeluxe.join-title:
    description: Permission of JoinMessagesDeluxe
    default: op
  joinfeaturesdeluxe.join-commands.join:
    description: Permission of JoinMessagesDeluxe
    default: op
  joinfeaturesdeluxe.join-commands.quit:
    description: Permission of JoinMessagesDeluxe
    default: op
