#░░░░░██╗░█████╗░██╗███╗░░██╗███╗░░░███╗███████╗░██████╗░██████╗░█████╗░░██████╗░███████╗░██████╗
#░░░░░██║██╔══██╗██║████╗░██║████╗░████║██╔════╝██╔════╝██╔════╝██╔══██╗██╔════╝░██╔════╝██╔════╝
#░░░░░██║██║░░██║██║██╔██╗██║██╔████╔██║█████╗░░╚█████╗░╚█████╗░███████║██║░░██╗░█████╗░░╚█████╗░
#██╗░░██║██║░░██║██║██║╚████║██║╚██╔╝██║██╔══╝░░░╚═══██╗░╚═══██╗██╔══██║██║░░╚██╗██╔══╝░░░╚═══██╗
#╚█████╔╝╚█████╔╝██║██║░╚███║██║░╚═╝░██║███████╗██████╔╝██████╔╝██║░░██║╚██████╔╝███████╗██████╔╝
#░╚════╝░░╚════╝░╚═╝╚═╝░░╚══╝╚═╝░░░░░╚═╝╚══════╝╚═════╝░╚═════╝░╚═╝░░╚═╝░╚═════╝░╚══════╝╚═════╝░
#██████╗░███████╗██╗░░░░░██╗░░░██╗██╗░░██╗███████╗
#██╔══██╗██╔════╝██║░░░░░██║░░░██║╚██╗██╔╝██╔════╝
#██║░░██║█████╗░░██║░░░░░██║░░░██║░╚███╔╝░█████╗░░
#██║░░██║██╔══╝░░██║░░░░░██║░░░██║░██╔██╗░██╔══╝░░
#██████╔╝███████╗███████╗╚██████╔╝██╔╝╚██╗███████╗
#╚═════╝░╚══════╝╚══════╝░╚═════╝░╚═╝░░╚═╝╚══════╝

join-messages:
  join: '&2%player_name% &ajoined!'
  quit: '&4%player_name% &cleft!'
  player-join-message:
    enabled: true
    lines:
      - '&6&m--------------------------------'
      - '&eWelcome to &5&lYourServer&e!'
      - '&6&lDISCORD: &f&nDiscord Link'
      - '&b&lTELEGRAM: &f&nTelegram Link'
      - '&c&lYOUTUBE: &f&nYoutube Link'
      - '&6&m--------------------------------'
  player-join-title:
    enabled: true
    title: '&5&lYourServer'
    subtitle: '&7Welcome in our &fcommunity&7!'
    fadeIn: 20
    stay: 60
    fadeOut: 20
